# Change these first
owner: gregorip02 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API (production)
    url: https://v2.restapros.com
  - name: API (development)
    url: https://v2-dev.restapros.com
    
  - name: Webapp (production)
    url: https://web.restapros.com
  - name: Webapp (development)
    url: https://web-dev.restapros.com
    
  - name: Invitation Page (production)
    url: https://invite.restapros.com
  - name: Invitation Page (development)
    url: https://invite-dev.restapros.com

  - name: Orders Page (production)
    url: https://orders.restapros.com
  - name: Orders Page (development)
    url: https://orders-dev.restapros.com
    
  - name: Referrals Page (production)
    url: https://referrals.restapros.com
  - name: Referrals Page (development)
    url: https://referrals-dev.restapros.com
    
  - name: Multimedia Service
    url: https://media.restapros.com
  
  - name: Assets
    url: https://assets.restapros.com/static/images/restapros.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
